# Generated by Django 5.0.3 on 2024-03-13 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NiceHabit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(blank=True, max_length=50, null=True, verbose_name='Место')),
                ('action', models.CharField(max_length=50, verbose_name='Действие')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Хорошая привычки',
                'verbose_name_plural': 'Хорошие привычки',
            },
        ),
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(verbose_name='Время')),
                ('place', models.CharField(max_length=50, verbose_name='Место')),
                ('action', models.CharField(max_length=50, verbose_name='Действие')),
                ('reward', models.CharField(blank=True, max_length=50, null=True, verbose_name='Вознаграждение')),
                ('periodicity', models.PositiveIntegerField(verbose_name='Переодичнось')),
                ('is_public', models.BooleanField(default=False, verbose_name='Публичность')),
                ('duration_time', models.TimeField(verbose_name='Время действия')),
                ('next_date', models.DateField(blank=True, null=True, verbose_name='Дата следующего напоминания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('associated_nice_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.nicehabit', verbose_name='Признак полезной привычки')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
            },
        ),
    ]
